version: 2
updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    groups:
      composer:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm:
        patterns: ['*']
        update-types: [minor, patch]
    commit-message:
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(ci)
