<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * A personal, automatic discount generated by App\Services\Personalization\OfferEngine.
 * `product_id` null means it applies to the whole order.
 */
class Offer extends Model
{
    public const KINDS = [
        'hesitation' => 'Still thinking it over',
        'cart_rescue' => 'Left in your bag',
        'regular' => 'One of your regulars',
        'welcome' => 'Welcome offer',
        'loyalty' => 'Loyal customer',
        'comeback' => 'Welcome back',
    ];

    protected $fillable = ['visitor', 'user_id', 'product_id', 'kind', 'percent', 'reason', 'expires_at', 'redeemed_at', 'order_id'];

    protected function casts(): array
    {
        return ['expires_at' => 'datetime', 'redeemed_at' => 'datetime', 'percent' => 'integer'];
    }

    public function scopeActive(Builder $query): void
    {
        $query->whereNull('redeemed_at')->where('expires_at', '>', now());
    }

    public function product(): BelongsTo
    {
        return $this->belongsTo(Product::class);
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function toClient(): array
    {
        return [
            'id' => $this->id,
            'kind' => $this->kind,
            'label' => __(self::KINDS[$this->kind] ?? 'Personal offer'),
            'percent' => $this->percent,
            // Fixed reasons (welcome, come-back) are in lang/*.json; ones naming a product stay as written.
            'reason' => __($this->reason),
            'product_id' => $this->product_id,
            'product' => $this->relationLoaded('product') ? $this->product?->only('name', 'slug') : null,
            'expires_at' => $this->expires_at->toIso8601String(),
        ];
    }
}
